
output.elasticsearch:
  hosts: ["${ELASTIC_HOST}"]

setup.kibana:
  hosts: ["${KIBANA_HOST}"]

filebeat.inputs:
- type: log
  paths:
    - /root/logs/*-api-out.log
  fields:
    origin: system
    application: ${CHAIN_NAME}_api
  fields_under_root: true

- type: log
  paths:
    - /root/logs/*-indexer-out.log
  fields:
    origin: system
    application: ${CHAIN_NAME}_indexer
  fields_under_root: true
