# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  truffle_test:
    name: Truffle Test
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        
      - name: Setup Truffle
        run: npm install -g truffle
          
      - name: Setup Truffle HD Wallet
        run: npm install @truffle/hdwallet-provider
        
      - name: Run run.sh
        run: sudo ./run.sh debug

      - name: Run Truffle test
        run: cd tests/test_erc20/ && truffle test --network private
