# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      - python_toolchain
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  indexing_test:
    name: Indexing Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build docker containers
        run: |
          docker build --tag eosio:2.0.13-evm docker/eosio
          docker build --tag telos.net/hyperion:0.1.0 docker/hyperion
      - name: Run test
        run: python scripts/telos_evm.py --loglevel=INFO


        # runs-on: ubuntu-latest
        # steps:
        #   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        #   - uses: actions/checkout@v2
        #   
        #   - name: Setup Node
        #     uses: actions/setup-node@v2
        #     with:
        #       node-version: '14'
        #       
        #   - name: Setup Docker
        #     uses: docker-practice/actions-setup-docker@master
        #     
        #   - name: Setup Truffle
        #     run: npm install -g truffle
        #       
        #   - name: Setup Truffle HD Wallet
        #     run: npm install @truffle/hdwallet-provider
        #     
        #   - name: Run run.sh
        #     run: sudo ./run.sh debug

        #   - name: Run Truffle test
        #     run: cd tests/test_erc20/ && truffle test --network private
