name: Truffle Tests 

on:
  push:
    branches:
      - python_toolchain

  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  truffle_test:
    name: Truffle Tests
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Truffle
        run: npm install -g truffle
          
      - name: Setup Truffle HD Wallet
        working-directory: ./tests/test_erc20
        run: npm install @truffle/hdwallet-provider

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Init local chain
        run: tevmc init local

      - name: Bootstrap 
        working-directory: local
        run: ./run.sh

      - name: Wait blocks
        run: tevmc wait-block 60

      - name: Run test_erc20
        working-directory: ./tests/test_erc20
        run: truffle --network private test
