name: Truffle Tests 

on:
  push:
    branches:
      - python_toolchain

  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  truffle_test:
    name: Truffle Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Pull docker containers
        run: tevmc pull --headless

      - name: Config hyperion
        run: tevmc config --index-only-evm 

      - name: Build docker containers
        run: tevmc build --headless --testing

      - name: Pull services up
        run: tevmc up --loglevel=info

      - name: Wait block indexing
        run: tevmc wait-block 100

      - name: Run test_itxs
        run: |
          docker run \
            --network host \
            tevm:testing \
            bash -c 'cd test_itxs && truffle --network private test'

      - name: Run test_erc20
        run: |
          docker run \
            --network host \
            tevm:testing \
            bash -c 'cd test_erc20 && truffle --network private test'

      - name: Pull services down
        run: tevmc down
